### ISSUE TITLE
after install not work authenticate

### ISSUE THREAD

**Issue by mshma** [enghamzasalem/whats-gpt-firebase#2]
show me this in log

xample app listening on port 3500!
{
  phoneNumber: '009XXX',
  message: 'تحدث بالعربي '
}
Client is not ready to use!
Client {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  options: {
    authStrategy: LocalAuth {
      dataPath: '/root/whats-gpt-firebase/.wwebjs_auth',
      clientId: 'session-009XXX',
      client: [Circular]
    },
    puppeteer: { headless: true, defaultViewport: null },
    webVersion: '2.2322.15',
    webVersionCache: { type: 'local' },
    authTimeoutMs: 0,
    qrMaxRetries: 0,
    takeoverOnConflict: false,
    takeoverTimeoutMs: 0,
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36',
    ffmpegPath: 'ffmpeg',
    bypassCSP: false,
    proxyAuthentication: undefined
  },
  authStrategy: LocalAuth {
    dataPath: '/root/whats-gpt-firebase/.wwebjs_auth',
    clientId: 'session-009XXX',
    client: [Circular]
  },
  pupBrowser: null,
  pupPage: null,
  [Symbol(kCapture)]: false
}
(node:1957) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/root/whats-gpt-firebase/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/whats-gpt-firebase/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/root/whats-gpt-firebase/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by enghamzasalem** [comment]
"Client is not ready to use!" means you need to wait till be ready 
also check if you running this in local machine not replit or online server

**Comment by mshma300** [comment]
There is any way to install in online i use it in aws Ubuntu 22

**Comment by mshma** [comment]
work good thank you
